In [24]:
import numpy as np
# Array creation 
array_1d=np.array([1,2,3,4,5]) # 1D array creation
print(f"This is 1D array = {array_1d}")

arr_2d=np.array([[1,2,3,4],
                 [6,7,8,9],
                 [10,11,12,14]]) # 2D array creation
print(f"This is 2D array =\n{arr_2d}")

arr_zero=np.zeros((3,3))  # 3x3 zeros array creation
print(f"This is all elements of matrix 3x3 is zero \n{arr_zero}")

arr_one=np.ones((2,3))  # 2x3 ones array creation
print(f"This is all elements of matrix 2x3 is ones \n{arr_one}")
same=np.full((3,4),7) # 3x4 same number array creation
print(f"All elements of this matrix is same number\n {same}")
rge=np.arange(0,21,2) #Only create 1D array  even number 0 to 20
print(f"0 to 20 Even number is \n {rge}")

This is 1D array = [1 2 3 4 5]
This is 2D array =
[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 14]]
This is all elements of matrix 3x3 is zero 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
This is all elements of matrix 2x3 is ones 
[[1. 1. 1.]
 [1. 1. 1.]]
All elements of this matrix is same number
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
0 to 20 Even number is 
 [ 0  2  4  6  8 10 12 14 16 18 20]


In [23]:
# Array Indexing & Slicing
array_1d=np.array([1,2,3,4,5]) #Indexing 1D array 
print(f"Get the value of index 3 = {array_1d[3]}")

arr_2d=np.array([[1,2,3,4],
                 [6,7,8,9],
                 [10,11,12,14]])
get=arr_2d[1,2] #Get the value of row 2 col 3 value 
print(f"This is row2 col3 value = {get}")
get_col=arr_2d[:, 1] #Get the only value of col 2
print(f"value of col 2 is {get_col}")

Get the value of index 3 = 4
This is row2 col3 value = 8
value of col 2 is [ 2  7 11]


In [38]:
# Vectorized Mathematical Operations
array_1=np.array([1,2,3,4,5])
array_2=np.array([6,7,8,9,0])
total= array_1+array_2
print(f"Sum of 2 1D vector is = \n{total}") 
mul= array_1 * array_2
print(f"Multiplication of 2 1D vector is = \n{mul}")

# Aggregation (Summary Statistics)
#Find maximum number of two vectors
m=np.concatenate((array_1,array_2))
maximun=np.max(m)
print(f"Multiplication of 2 1D vector is = \n{maximun}")
#Find manimum number of two vectors
minimum=np.min(m)
print(f"Multiplication of 2 1D vector is = \n{minimum}")


Sum of 2 1D vector is = 
[ 7  9 11 13  5]
Multiplication of 2 1D vector is = 
[ 6 14 24 36  0]
Multiplication of 2 1D vector is = 
9
Multiplication of 2 1D vector is = 
0


In [49]:
# Reshaping Arrays
arr=np.arange(1,17)
print(f"1D array is = {arr}")
#Reshape the 1D array in 4x4
reshaped=arr.reshape(4,4)
print(f"4x4 array is = \n{reshaped}")

1D array is = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
4x4 array is = 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [55]:
# Matrix Operations
array_1=np.array([1,2,3,4,5])
array_2=np.array([6,7,8,9,0])
# Dot Product
dot_p=np.dot(array_1,array_2)
print(f"Dor product of two vector is {dot_p}")

#Transpose of 2D  
arr_2d=np.array([[1,2,3,4],
                 [6,7,8,9],
                 [10,11,12,14]])
tra=arr_2d.T
print(f"Transpose of 2D vector is \n{tra}")           

Dor product of two vector is 80
Transpose of 2D vector is 
[[ 1  6 10]
 [ 2  7 11]
 [ 3  8 12]
 [ 4  9 14]]


In [61]:
# Broadcasting
arr_2d=np.array([[1,2,3],
                 [6,7,5]])
a=np.array([1,2,3])
result= arr_2d + a
print(f"Adding \n{result}")


Adding 
[[2 4 6]
 [7 9 8]]


In [76]:
# Random Number Generation
# Random Integer Generation
ran=np.random.randint(1,101,10)
print(f"10 Integer random from 1-100 \n{ran}")

# Random float Generation
flo=np.random.rand(1,5)
print(f"float random from 1-5 \n{flo}")

# Random 2D Array
ra= np.random.rand(2, 3)
print(f"2D float random from 1-5 \n{ra}")

# Random Choice
ch=np.random.choice([1,29,0,7,6,5,8,8,77],5)
print(f"Choice randim number from givrn list \n{ch}")


10 Integer random from 1-100 
[79 19 66 78 66 43 34 67 85 19]
float random from 1-5 
[[0.76521729 0.03715448 0.44837438 0.60298414 0.83787323]]
2D float random from 1-5 
[[0.69806146 0.16093658 0.55591955]
 [0.47613128 0.30297059 0.12411656]]
Choice randim number from givrn list 
[ 7 77  8 77 77]
